Review/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ReviewApp.urls')),
]

ReviewApp/urls.py
from django.urls import path
from .views import IndexView
from . import views

app_name = 'ReviewApp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('search', views.Search, name='search'),
    path('shop_info/<str:restid>', views.ShopInfo, name='shop_info'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),

]

ReviewApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Category, Pref, Reviewモデルの作成をします。

class Category(models.Model):
    category_l = models.CharField('業態カテゴリ', max_length=10, blank=False)
    name = models.CharField('業態名', max_length=30, blank=False)

    def __str__(self):
        return str(self.name)

class Pref(models.Model):
    pref = models.CharField('都道府県コード', max_length=6, blank=False)
    name = models.CharField('都道府県名', max_length=10, blank=False)

    def __str__(self):
        return str(self.name)

SCORE_CHOICES = [
    (1, '★'),
    (2, '★★'),
    (3, '★★★'),
    (4, '★★★★'),
    (5, '★★★★★'),
]

class Review(models.Model):
    shop_id = models.CharField('店舗ID', max_length=10, blank=False)
    shop_name = models.CharField('店舗名', max_length=200, blank=False)
    image_url = models.CharField('画像1URL', max_length=300, blank=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    comment = models.TextField(verbose_name='レビューコメント', blank=False)
    score = models.PositiveSmallIntegerField(verbose_name='レビュースコア', choices=SCORE_CHOICES, default='3')
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('shop_id', 'user')

    def __str__(self):
        return str(self.shop_id)

    def get_percent(self):
        percent = round(self.score / 5 * 100)

ReviewApp/forms.py
from django import forms
from .models import Category, Pref, User, Review
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
class SearchForm(forms.Form):
    selected_pref = forms.ModelChoiceField(
        label='都道府県',
        required=False,
        queryset=Pref.objects
    )
    selected_category = forms.ModelChoiceField(
        label='カテゴリ',
        required=False,
        queryset=Category.objects,
    )
    freeword = forms.CharField(min_length= 2, max_length= 100, label='', required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        selected_pref = self.fields['selected_pref']
        selected_category = self.fields['selected_category']

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in self.fields.values():
                field.widget.attrs['class'] = 'form-control'
                field.widget.attrs['placeholder'] = field.label


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['score', 'comment']

ReviewApp/views.py
from django.shortcuts import render, redirect
from django.views.generic import (
CreateView,
ListView,
UpdateView,
DeleteView,
TemplateView,
)
from .models import Pref, Category, User, Review
from .forms import SearchForm, SignUpForm, LoginForm, ReviewForm
import json
import requests
from django.contrib.auth import login, authenticate
from django.contrib.auth.views import LoginView, LogoutView
from django.db.models import Avg
from django.contrib import messages

def get_keyid():
    return 'f10f93e3a0c0b5419a7a4ded6b3864a1'

class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, *args, **kwargs):
        searchform = SearchForm()

        query = get_gnavi_data('', 'RSFST09000', '', 'クリスマス', 12)
        res_list = rest_search(query)
        pickup_list = extract_restaurant_info(res_list)
        review_list = Review.objects.all()[:10]

        params = {
            'searchform': searchform,
            'pickup_list': pickup_list,
            'review_list': review_list
        }
        return params


def Search(request):
    if request.method == 'GET':
        searchform = SearchForm(request.POST)

        if searchform.is_valid():
            category_l = request.GET['category_l']
            pref = request.GET['pref']
            freeword = request.GET['freeword']
            query = get_gnavi_data('', category_l, pref, freeword, 10)
            res_list = rest_search(query)
            total_hit_count = len(res_list)
            restaurants_info = extract_restaurant_info(res_list)

    params = {
        'total_hit_count': total_hit_count,
        'restaurants_info': restaurants_info,
    }

    return render(request, 'search.html', params)

def get_gnavi_data(id, category_l, pref, freeword, hit_per_page):
    keyid = get_keyid()
    #一度に取得できる最大件数
    hit_per_page = hit_per_page
    #店舗のid(グルナビ内で一意になっている)
    id = id
    #大業態カテゴリ
    category_l = category_l
    #pref
    pref = pref
    #freeword
    freeword = freeword
    #今回は関東のみ
    area = 'AREA110'
    #パラメータ設定
    query = {"keyid": keyid, "id": id, "area": area, "pref": pref, "category_l": category_l,
             "hit_per_page": hit_per_page, "freeword": freeword}

    return query

def rest_search(query):
    res_list = []
    res = json.loads(requests.get("https://api.gnavi.co.jp/RestSearchAPI/v3/", params=query).text)
    if 'error' not in res:
        res_list.extend(res['rest'])
    return res_list

def extract_restaurant_info(restaurants: 'restaurant response') -> 'restaurant list':
    restaurant_list = []
    for restaurant in restaurants:
        id = restaurant['id']
        name = restaurant['name']
        name_kana = restaurant['name_kana']
        url = restaurant['url']
        url_mobile = restaurant['url_mobile']
        shop_image1 = restaurant['image_url']['shop_image1']
        shop_image2 = restaurant['image_url']['shop_image2']
        address = restaurant['address']
        tel = restaurant['tel']
        station_line = restaurant['access']['line']
        station = restaurant['access']['station']
        latitude = restaurant['latitude']
        longitude = restaurant['longitude']
        pr_long = restaurant['pr']['pr_long']

        restaurant_list.append([id, name, name_kana, url, url_mobile, shop_image1, shop_image2, address, tel, station_line, station, latitude, longitude, pr_long])

    return restaurant_list

def ShopInfo(request, restid):
    keyid = get_keyid()
    id = restid
    query = get_gnavi_data(id,'' ,'', '', 1)
    res_list = rest_search(query)
    restaurants_info = extract_restaurant_info(res_list)
    review_count = Review.objects.filter(shop_id=restid).count()
    score_ave = Review.objects.filter(shop_id=restid).aggregate(Avg('score'))
    average = score_ave['score__avg']

    if average:
        average_rate = average / 5 * 100
    else:
        average_rate = 0

    if request.method == 'GET':
        review_form = ReviewForm()
        review_list = Review.objects.filter(shop_id=restid)

    else:
        form = ReviewForm(data=request.POST)
        score = request.POST['score']
        comment = request.POST['comment']

        if form.is_valid():
            review = Review()
            review.shop_id = restid
            review.shop_name = restaurants_info[0][1]
            review.shop_kana = restaurants_info[0][2]
            review.shop_address = restaurants_info[0][7]
            review.image_url = restaurants_info[0][5]
            review.user = request.user
            review.score = score
            review.comment = comment

            is_exist = 0
            is_exist = Review.objects.filter(shop_id=review.shop_id).filter(user=review.user).count()

            if not is_exist == 0:
                messages.error(request, '既にレビューを投稿済みです。')
                return redirect('ReviewApp:shop_info', restid)
            else:
                review.save()
                messages.success(request, 'レビューを投稿しました。')
                return redirect('ReviewApp:shop_info', restid)

        else:
            messages.error(request, 'エラーがあります。')
            return redirect('ReviewApp:shop_info', restid)
        return render(request, 'index.html', {})

    params = {
        'title': '店舗詳細',
        'review_count': review_count,
        'restaurants_info': restaurants_info,
        'review_form': review_form,
        'review_list': review_list,
        'average': average,
        'average_rate': average_rate,
    }

    return render(request, 'shop_info.html', params)

class SignUp(CreateView):
    form_class = SignUpForm
    template_name = 'signup.html'

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('ReviewApp:index')
        return render(request, 'signup.html', {'form': form})

class Login(LoginView):
    form_class = LoginForm
    template_name = 'login.html'

class Logout(LogoutView):
    template_name = 'logout.html'

ReviewApp/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block customcss %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock customcss %}

{% block content %}


{#carousel.html#}
<main role="main">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
          <img src="{% static 'image/cook-2364221_1920.jpg' %}" width="1214" alt="Rev">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img"><rect width="100%" height="100%" fill="#777"/></svg>
        <div class="container">
          <div class="carousel-caption">
            <h1>Rev</h1>
            <p>おいしいお店を探しましょう</p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'image/pancake-1984716_1920.jpg' %}" alt="Rev">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img"><rect width="100%" height="100%" fill="#777"/></svg>
        <div class="container">
          <div class="carousel-caption">
            <h1>Rev</h1>
            <p>このお店はとてもおいしいです</p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
          <img src="{% static 'image/pizza-346985_1920.jpg' %}" alt="Rev">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img"><rect width="100%" height="100%" fill="#777"/></svg>
        <div class="container">
          <div class="carousel-caption">
            <h1>Rev</h1>
            <p>おいしい料理が食べられます</p>
          </div>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
{#ここまで#}


    <section class="search-sec">
        <div class="container">
            <form method="GET" action="{% url 'ReviewApp:search' %}" name="searchform">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                                <select name="pref" class="form-control search-slt">
                                    <option value="">都道府県</option>
                                    {% for item in pref_list %}
                                        <option value="{{ item.pref }}">{{ item.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                                <select name="category_l" class="form-control search-slt">
                                    <option value="">カテゴリ</option>
                                    {% for item in category_list %}
                                    <option value="{{ item.category_l }}">{{ item.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        <div class="col-log-3 col-md-3 col-sm-12 p-0">
                            <input class="form-control search-slt" type="text" placeholder="フリーワード" aria-label="Search" name="freeword">
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                            <button type="submit" class="btn search-btn">検索</button>
                        </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>

    <div class="container">
        <h2 class="section-title">おすすめ</h2>
    </div>
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                {% for item in pickup_list %}
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                    <img src="{{ item.5 }}" alt="{{ item.1 }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ item.1 }}</h5>
                            <p class="card-text">{{ item.7 }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <a href="{% url 'ReviewApp:shop_info' item.0 %}" class="btn common-btn">詳細を見る</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>
    <br>
    <div class="container">
        <h2 class="section-title">最近のレビュー</h2>
        <div class="row">
            <div class="MultiCarousel" data-items="'1,3,5,6" data-slide="1" id="MultiCarousel" data-interval="1000">
                <div class="MultiCarousel-inner">
                    {% for item in review_list %}
                    <div class="item">
                        <div class="pad15">
                            <img src="{{ item.image_url }}" style="width: 100%;">
                            <p>{{ item.shop_name }}</p>
                            <p>「{{ item.comment }}」</p>
                            <a href="{% url 'ReviewApp:shop_info' item.shop_id %}" class="btn common-btn">詳細を見る</a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <button class="btn btn-primary leftLst"></button>
                <button class="btn btn-primary rightLst"></button>
            </div>
        </div>
    </div>
</main>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
<script src="{% static 'js/index.js' %}"></script>

{% endblock content %}

ReviewApp/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block customcss %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock customcss %}

{% block content %}
<div class="container">
    <div class="loginPage_contents">
        <h1 class="h3 loginPage_contents_title">ログイン</h1>
        <br>
        <hr>
        <br>
        <form action="" method="post">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-body">
                        {{ form.non_field_errors }}
                        {% for field in form %}
                        <p>{{ field.label }}</p>
                        {{ field }}
                        {{ field.errors }}
                        <hr>
                        {% endfor %}
                        <button type="submit" class="btn common-btn">ログイン</button>
                        <input type="hidden" name="next" value="{{ next }}"/>
                        {% csrf_token %}
                    </div>
                </div>
            </div>
        </form>
        <Hr>
            <p>まだアカウントがない方は<a href="{% url 'ReviewApp:signup' %}">こちら</a></p>
    </div>
</div>
{% endblock content %}

ReviewApp/templates/logout.html
{% extends 'base.html' %}
{% load static %}
{% block customcss %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock customcss %}
{% block content %}
<div class="container">
    <div class="loginPage_contents">
        <h3 class="h3 loginPage_contents_title">またのご利用をお待ちしております</h3>
        <br>
        <hr>
        <br>
        <a href="{% url 'ReviewApp:login' %}">ログインページ</a>
    </div>
</div>
{% endblock %}

ReviewApp/templates/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/navbar.css' %}">



<div class="fixed-top">
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ffaa00">
  <a class="navbar-brand" href="{% url 'ReviewApp:index' %}"><img src="{% static 'image/Rev_logo.png' %}" alt="Revロゴ"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'ReviewApp:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
        {% if user.is_authenticated %}
        <li class="nav-item active">
            <a class="nav-item nav-link" href="{% url 'ReviewApp:logout' %}">ログアウト</a>
        </li>
        {% else %}
        <li class="nav-item active">
            <a class="nav-item nav-link" href="{% url 'ReviewApp:login' %}">ログイン</a>
        </li>
        <li class="nav-item active">
            <a class="nav-item nav-link" href="{% url 'ReviewApp:signup' %}">新規会員登録</a>
        </li>
        {% endif %}
    </ul>

      <form action="{% url 'ReviewApp:search' %}" method="get" name="searchform">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                  <select name="pref" class="form-control nav-link">
                      <option value="" disabled selected style="display: none;">都道府県</option>
                      {% for item in pref_list %}
                      <option value="{{ item.pref }}">{{ item.name }}</option>
                      {% endfor %}
                  </select>
              </li>
              <li class="nav-item">
                  <select name="category_l" class="form-control nav-link">
                      <option value="" disabled selected style="display: none;">カテゴリ</option>
                      {% for item in category_list %}
                      <option value="{{ item.category_l }}">{{ item.name }}</option>
                      {% endfor %}
                  </select>
              </li>
          <li class="nav-item">
              <input type="text" class="form-control nav-link" placeholder="フリーワード" aria-label="Search" name="freeword">
          </li>
          <span> </span>
          <li class="nav-item">
              <button type="submit" class="btn common-btn" style='border-color: white; color: black'>検索</button>
          </li>
          </ul>
      </form>
  </div>
</nav>
</div>

ReviewApp/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block customcss %}
    <link rel="stylesheet" href="{% static 'css/search.css' %}">
{% endblock customcss %}

{% block content %}
<div class="container">
    <div class="row">
    {% if restaurants_info %}
        <h3>{{ total_hit_count }}件あります。<small>最大10件表示</small></h3>
        <br><br>
        {% for item in restaurants_info %}
        <div class="col-md-12">
            <div class="section-outer-box">
                <div class="row">
                    <div class="col-xs-col-md-3">
                        <img src="{{ item.5 }}" alt="{{ item.1 }}" class="img-rounded img-responsive" width="150px" />
                    </div>
                    <div class="col-xs-9 col-md-9 section-box">
                        <h4>{{ item.1 }}<br><a href="{% url 'ReviewApp:shop_info' item.0 %}" class="btn common-btn">詳細を見る</a></h4>
                        <p>{{ item.2}}</p>
                        <p>{{ item.7 }}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <div class="row">
            <div class="col-lg-12">
                <p>該当するものがありません。</p>
            </div>
        </div>
    {% endif %}
    </div>
</div>
{% endblock %}

ReviewApp/templates/shop_info.html
{% extends 'base.html' %}
{% load static %}

{% block customcss %}
    <link rel="stylesheet" href="{% static 'css/shop_info.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="section-title">{{ restaurants_info.0.1 }}</h2>
        </div>
    </div>
    <br>

    <div class="row">
        <div class="col-md-4">
            <div id="shop_carousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{{ restaurants_info.0.5 }}" alt="{{ restaurants_info.0.1 }}" class="d-block w-100">
                    </div>
                    {% if restaurants_info.0.6 %}
                    <div class="carousel-item">
                        <img src="{{ restaurants_info.0.6 }}" class="d-block w-100" alt="{{ restaurants_info.0.1 }}">
                    </div>
                    {% endif %}
                </div>
                <a href="#shop_carousel" class="carousel-control-prev" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">前の画像</span>
                </a>
                <a href="#shop_carousel" role="button" class="carousel-control-next" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">次の画像</span>
                </a>
            </div>
            <br>
            {% if average_rate != 0 %}
            <p>ユーザーによる評価</p>
            <div class="star-rating">
                <div class="star-rating-front" style="width: {{ average_rate }}%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
            </div>({{ average|floatformat }}点 / {{ review_count }}件)
            {% else %}
            <p>(まだ評価はありません。最初のレビューをお願いします)</p>
            {% endif %}
        </div>

        <div class="col-md-8">
            <p>{{ restaurants_info.0.13|linebreaksbr }}</p>
            <a href="{{ restaurants_info.0.3 }}" class="btn common-btn" target="_blank">お店ページ <i class="fas fa-external-link-alt"></i></a>
            <a href="{{ restaurants_info.0.4 }}" class="btn common-btn" target="_blank">お店ページ(モバイル) <i class="fas fa-external-link-alt"></i></a>
        </div>
    </div>
    <br>
    <br>
    <div class="row">
        <div class="col-md-12">
            <h2 class="section-title">店舗基本情報</h2>
            <table class="table">
                <tr>
                    <td>店舗名</td>
                    <td>{{ restaurants_info.0.1 }}</td>
                </tr>
                <tr>
                    <td>住所</td>
                    <td>{{ restaurants_info.0.7 }}</td>
                </tr>
                <tr>
                    <td>TEL</td>
                    <td>{{ restaurants_info.0.8 }}</td>
                </tr>
                <tr>
                    <td>アクセス</td>
                    <td>{{ restaurants_info.0.9 }}<br>{{ restaurants_info.0.10 }}</td>
                </tr>
            </table>
        </div>
    </div>
<br>
    <div class="row">
        <div class="col-md-12">
            <h2 class="section-title">口コミ情報</h2>
            {% if review_list %}
                <h3>レビューコメント</h3>
                {% for item in review_list %}
                    <div class="balloon5">
                        <div class="faceicon">
                            <img src="{% static 'image/reviewer.png' %}">
                            <p class="small">{{ item.user }}</p>
                        </div>
                        <div class="chatting">
                            <div class="says">
                                <div class="star-rating">
                                    <div class="star-rating-front" style="width: {{ item.get_percent }}%">★★★★★</div>
                                    <div class="star-rating-back">★★★★★</div>
                                </div>
                                <br>
                                <p>{{ item.comment }}</p>
                                <p class="small">{{ item.created_at }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <br>
                <p>まだレビューはありません。</p>
                <br>
            {% endif %}
            <hr>
            <h3>レビューを投稿する</h3>
            {% if user.is_authenticated %}
                <form class="login-form" action="" method="POST">
                    {{ review_form.non_field_errors }}
                    <div class="evaluation" style="float:left;">
                        <input id="score1" type="radio" name="score" value="5" />
                        <label for="score1"><span class="text">最高</span>★</label>
                        <input id="score2" type="radio" name="score" value="4" />
                        <label for="score2"><span class="text">良い</span>★</label>
                        <input id="score3" type="radio" name="score" value="3" />
                        <label for="score3"><span class="text">普通</span>★</label>
                        <input id="score4" type="radio" name="score" value="2" />
                        <label for="score4"><span class="text">悪い</span>★</label>
                        <input id="score5" type="radio" name="score" value="1" />
                        <label for="score5"><span class="text">最悪</span>★</label>
                    </div>
                    <br><br><br>
                    <label for="comment">コメント:</label>
                    <div class="form-group" type="text">{{ review_form.comment }}</div>

                    {% csrf_token %}
                    <br>
                    <button type="submit" class="btn common-btn">投稿する</button>
                    {% if form.errors %}
                    <br>
                    <p>エラー内容</p>
                        {% for field in form %}
                            {% for error in field.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        {% endfor %}
                    {% endif %}
                </form>
            {% else %}
                <p>レビューコメントを残すにはログインが必要です。</p>
                <br>
                <a class="btn common-btn" href="">新規登録</a>
                <a class="btn common-btn-outline" href="{% url 'ReviewApp:login' %}">ログイン</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}